/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Window;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import model.Item;
import controller.MainClass;

/**
 *
 * @author YASH
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    private static ArrayList<Item> items;
    public HomePage() {
        initComponents();
    }
    
    public HomePage(ArrayList<Item> item){
        items=item;
        initComponents();
        setSelected();
    }

    public static void setSelected(){
        
        rice.setSelectedIndex(items.get(0).getIndex());
        veges.setSelectedIndex(items.get(1).getIndex());
        meat.setSelectedIndex(items.get(2).getIndex());
        sauce.setSelectedIndex(items.get(3).getIndex());
        sourCream.setSelectedIndex(items.get(4).getIndex());
        guac.setSelectedIndex(items.get(5).getIndex());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        riceLabel = new javax.swing.JLabel();
        rice = new javax.swing.JComboBox<>();
        vegesLabel = new javax.swing.JLabel();
        veges = new javax.swing.JComboBox<>();
        meatLabel = new javax.swing.JLabel();
        meat = new javax.swing.JComboBox<>();
        sauceLabel = new javax.swing.JLabel();
        sauce = new javax.swing.JComboBox<>();
        sourCrLabel = new javax.swing.JLabel();
        sourCream = new javax.swing.JComboBox<>();
        guacLabel = new javax.swing.JLabel();
        guac = new javax.swing.JComboBox<>();
        placeOrder = new javax.swing.JButton();

        heading.setFont(new java.awt.Font("Trebuchet MS", 3, 40)); // NOI18N
        heading.setForeground(new java.awt.Color(153, 0, 0));
        heading.setText("Rice Bowl Restaurante");

        intro.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        intro.setForeground(new java.awt.Color(0, 0, 112));
        intro.setText("Place your order here for your delicious Rice Bowl :");

        riceLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        riceLabel.setText("Rice :");

        rice.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        rice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White Rice ($1.50)", "Brown Rice ($1.75)" }));
        rice.setInheritsPopupMenu(true);
        rice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceActionPerformed(evt);
            }
        });

        vegesLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        vegesLabel.setText("Mixed Vegetables :");

        veges.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        veges.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes ($1.5)", "No ($0)" }));

        meatLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        meatLabel.setText("Meat : ");

        meat.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        meat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beef ($2.50)", "Chicken ($2.75)" }));

        sauceLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        sauceLabel.setText("Sauce :");

        sauce.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        sauce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spicy ($0.50)", "Sweet ($0.50)", "Both ($0.80)" }));

        sourCrLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        sourCrLabel.setText("Sour Cream : ");

        sourCream.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        sourCream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes ($1.5)", "No ($0)" }));

        guacLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        guacLabel.setText("Guacamole : ");

        guac.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        guac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes ($1.5)", "No ($0)" }));

        placeOrder.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        placeOrder.setText("Place Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sauceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sourCrLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sourCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guacLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(placeOrder)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vegesLabel)
                        .addGap(26, 26, 26)
                        .addComponent(veges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(riceLabel)
                        .addGap(26, 26, 26)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riceLabel)
                    .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegesLabel)
                    .addComponent(veges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meatLabel)
                    .addComponent(meat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauceLabel)
                    .addComponent(sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourCrLabel)
                    .addComponent(sourCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guacLabel)
                    .addComponent(guac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(placeOrder)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        //The 'items' is the ArrayList of type Item used to record all the selections made by the user on the HomePage UI
        items=new ArrayList<>();
        //Rice Selection
        if(rice.getSelectedIndex()==0){items.add(new Item("rice","white",1.50,0));}
        else {items.add(new Item("rice","brown",1.75,1));}
        //Mixed Vegetables Selection
        if(veges.getSelectedIndex()==0){items.add(new Item("veges","yes",1.5,0));}
        else {items.add(new Item("veges","no",0,1));}
        //Meat Selection
        if(meat.getSelectedIndex()==0){items.add(new Item("meat","beef",2.50,0));}
        else {items.add(new Item("meat","chicken",2.75,1));}
        //Sauce Selection
        if(sauce.getSelectedIndex()==0){items.add(new Item("sauce","spicy",0.50,0));}
        else if(sauce.getSelectedIndex()==1){items.add(new Item("sauce","sweet",0.50,1));}
        else {items.add(new Item("sauce","both",0.80,2));}
        //Sour Cream Selection
        if(sourCream.getSelectedIndex()==0){items.add(new Item("sourCream","yes",1.50,0));}
        else {items.add(new Item("sourCream","no",0.00,1));}
        //Gaucomole Selection
        if(guac.getSelectedIndex()==0){items.add(new Item("guac","yes",1.50,0));}
        else {items.add(new Item("guac","no",0.00,1));}
        //System.out.println(items);
        //System.out.println("Total Cost: "+ MainClass.calculateBill(items));
        Window w = SwingUtilities.getWindowAncestor(HomePage.this);
        w.setVisible(false);
        MainClass.showConfirmOrderPage(items);       //'items' is passed as an argument so thst we can use the selections from this page to perform the further computations
    }//GEN-LAST:event_placeOrderActionPerformed

    private void riceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> guac;
    private javax.swing.JLabel guacLabel;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel intro;
    private static javax.swing.JComboBox<String> meat;
    private javax.swing.JLabel meatLabel;
    private javax.swing.JButton placeOrder;
    private static javax.swing.JComboBox<String> rice;
    private javax.swing.JLabel riceLabel;
    private static javax.swing.JComboBox<String> sauce;
    private javax.swing.JLabel sauceLabel;
    private javax.swing.JLabel sourCrLabel;
    private static javax.swing.JComboBox<String> sourCream;
    private static javax.swing.JComboBox<String> veges;
    private javax.swing.JLabel vegesLabel;
    // End of variables declaration//GEN-END:variables
}
